
name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    -builds: npm run build
    Start: npm start
    - name: AssignmentPart11.java run
      - run: npm test
