name: The TestJava.yml file
on:
  pull_request:
    branches: [ main ]

jobs:
  long-running-test-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Long-running task
        run: do-the-thing.sh
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: "/output"
          key: ${{ runner.os }}-$GITHUB_RUN_ID
  unit-tests:
    needs: long-running-test-dependency
    runs-on: ubuntu-latest
    steps:
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: "/output"
          key: ${{ runner.os }}-$GITHUB_RUN_ID
      - name: run tests
        runs: npm test:unit
  integration-tests:
    needs: long-running-test-dependency
    runs-on: ubuntu-latest
    steps:
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: "/output"
          key: ${{ runner.os }}-$GITHUB_RUN_ID
