# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: The TestJava.yml file


    
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: ./Assignment_Part.1.1 testDebugUnitTest

      - name: Assignment_Part.1.1  Test Report
        uses: asadmansr/Assignment_Part.1.1-test-report-action@v1.2.0
